providers = ["node"]

[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.install]
dependsOn = ["setup"]
cmds = [
  "cd apps/web && npm install --legacy-peer-deps"
]

[phases.build]
dependsOn = ["install"]
cmds = [
  "cd apps/web && npm run build"
]

[start]
cmd = "cd apps/web && npm start"